# Generated by Django 3.1.7 on 2021-03-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sellers',
            new_name='Seller',
        ),
    ]
